name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: logiontology
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('logiontology/pyproject.toml', 'logiontology/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: isort
        run: isort --check-only .

  type-security:
    name: Type & Security Gates
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: logiontology
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('logiontology/pyproject.toml', 'logiontology/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: mypy
        run: mypy --strict src
      - name: Bandit
        run: bandit -r src
      - name: pip-audit
        run: pip-audit

  tests:
    name: Tests & Coverage
    runs-on: ubuntu-latest
    needs: type-security
    defaults:
      run:
        working-directory: logiontology
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('logiontology/pyproject.toml', 'logiontology/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Pytest
        run: coverage run -m pytest
      - name: Coverage Gate
        run: coverage report --fail-under=70
      - name: Upload coverage
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: logiontology/.coverage
